### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by huan** [hczhcz/wechaty-telegram#1]
Hi @hczhcz !

Integrate Wechaty with Telegram is a cool idea, and you did a great work.

Would you like to share more with the Wechaty community?

Please contact me on Wechat, my wechat id: 918999

Thanks!

**Comment by hczhcz** [comment]
Thanks for @zixia's invitation!

---

The following discussion could be found here:

[invite @hczhcz to write about how to integrate wechaty with telegram](https://github.com/Chatie/blog/issues/36)

and here:

[Run Your Telegram Bot with Wechaty](http://blog.chatie.io/2017/07/17/run-your-telegram-bot-with-wechaty.html)
